### ISSUE TITLE
PostItTask.java:20: <body>remove minimize and maximize...

### ISSUE THREAD

**Issue by 0pdd** [paulodamaso/donkey-tasks#11]
The puzzle `6-c02063cc` (from #6) in [`src/java/main/PostItTask.java`](https://github.com/paulodamaso/donkey-tasks/blob/a11c2380fb8c106a6a1fde136ad3e7f9a81d815e/src/java/main/PostItTask.java#L20-L20) has to be resolved: "remove minimize and maximize buttons."

https://github.com/paulodamaso/donkey-tasks/blob/a11c2380fb8c106a6a1fde136ad3e7f9a81d815e/src/java/main/PostItTask.java#L20-L20

The puzzle was created by Paulo Lobo on 15-Dec-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by paulodamaso** [comment]
Removed changing PostItTask class to JDialog instead of JFrame.

**Comment by paulodamaso** [comment]
Removed changing PostItTask class to JDialog instead of JFrame.
