### ISSUE TITLE
Main.java:22: <body>implement a complete application,...

### ISSUE THREAD

**Issue by 0pdd** [paulodamaso/donkey-tasks#14]
The puzzle `6-490ff87b` from #6 has to be resolved:

https://github.com/paulodamaso/donkey-tasks/blob/c7b1cfd881f72998b9dcb9cfca1b7534ded4d018/src/java/main/Main.java#L22-L22

The puzzle was created by Paulo Lobo on 18-Dec-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by paulodamaso** [comment]
Application implemented but need installer.
