### ISSUE TITLE
SimpleStickerTask.java:20: <body>it would be interesting...

### ISSUE THREAD

**Issue by 0pdd** [paulodamaso/donkey-tasks#22]
The puzzle `6-b0e96941` from #6 has to be resolved:

https://github.com/paulodamaso/donkey-tasks/blob/b1b5d9a90dbd5c65868e8ec6437cbc7886b9c322/src/java/main/ui/swing/SimpleStickerTask.java#L20-L20

The puzzle was created by Paulo Lobo on 19-Dec-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by paulodamaso** [comment]
Added decorations in issues 24,25,26 and 27.
