### ISSUE TITLE
StickerTasks.java:24-25: <body>this implementation does...

### ISSUE THREAD

**Issue by 0pdd** [paulodamaso/donkey-tasks#23]
The puzzle `6-a470e601` from #6 has to be resolved:

https://github.com/paulodamaso/donkey-tasks/blob/3b27a5a8ce7f938d3aa01d9deee7ef412d086373/src/java/main/ui/swing/StickerTasks.java#L24-L25

The puzzle was created by Paulo Lobo on 20-Dec-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by paulodamaso** [comment]
Separated Task from Sticker, making this issue invalid.
