### ISSUE TITLE
MemoryTasks.java:19-19: arrumar essa implementação sem usar...

### ISSUE THREAD

**Issue by 0pdd** [paulodamaso/donkey-tasks#3]
The puzzle `2-0161dd6c` (from #2) in [`src/java/main/MemoryTasks.java`](https://github.com/paulodamaso/donkey-tasks/blob/master/src/java/main/MemoryTasks.java) (lines 19-19) has to be resolved: "arrumar essa implementação sem usar classe anônima"

The puzzle was created by Paulo Lobo on 02-Dec-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by paulodamaso** [comment]
Corrected adding the method add(Task):Tasks to Tasks interface.
