### ISSUE TITLE
Main.java:11-12: essa instanciação da lista de tarefas...

### ISSUE THREAD

**Issue by 0pdd** [paulodamaso/donkey-tasks#4]
The puzzle `2-a6158369` (from #2) in [`src/java/main/Main.java`](https://github.com/paulodamaso/donkey-tasks/blob/master/src/java/main/Main.java) (lines 11-12) has to be resolved: "essa instanciação da lista de tarefas não está legal melhor seria a utilização de uma interface aqui"

The puzzle was created by Paulo Lobo on 02-Dec-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by paulodamaso** [comment]
Fixed.
