### ISSUE TITLE
ConsoleTaskList.java:22-24: ainda não sei qual a melhor maneira...

### ISSUE THREAD

**Issue by 0pdd** [paulodamaso/donkey-tasks#5]
The puzzle `2-a8a366ac` (from #2) in [`src/java/main/ConsoleTaskList.java`](https://github.com/paulodamaso/donkey-tasks/blob/master/src/java/main/ConsoleTaskList.java) (lines 22-24) has to be resolved: "ainda não sei qual a melhor maneira de fazer essa impressão: - PrintableTask.print(), e chamando uma tarefa printable ConsolePrintableTask() (bridge)? - ConsoleTaskList.print(), imprimindo as tarefas de acordo com essa lógica aqui"

The puzzle was created by Paulo Lobo on 02-Dec-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by paulodamaso** [comment]
Resolved: the Tasks interface is not printable, but if you want to print its content you must implement the Printable interface in your Tasks implementation.
