### ISSUE TITLE
Main.java:16: <body>implement an swing task list</body>

### ISSUE THREAD

**Issue by 0pdd** [paulodamaso/donkey-tasks#6]
The puzzle `4-2c0adc7d` (from #4) in [`src/java/main/Main.java`](https://github.com/paulodamaso/donkey-tasks/blob/9987d09c4a333727d029f64148ca38a2bebeae68/src/java/main/Main.java#L16-L16) has to be resolved: "implement an swing task list"

https://github.com/paulodamaso/donkey-tasks/blob/9987d09c4a333727d029f64148ca38a2bebeae68/src/java/main/Main.java#L16-L16

The puzzle was created by Paulo Lobo on 15-Dec-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by paulodamaso** [comment]
Implemented in a simple way using a list os SwingTask.
