### ISSUE TITLE
Task.java:11-12: <body>i am not so sure about extending...

### ISSUE THREAD

**Issue by 0pdd** [paulodamaso/donkey-tasks#7]
The puzzle `2-4e977bdc` (from #2) in [`src/java/main/Task.java`](https://github.com/paulodamaso/donkey-tasks/blob/9987d09c4a333727d029f64148ca38a2bebeae68/src/java/main/Task.java#L11-L12) has to be resolved: "i am not so sure about extending the printable interface here, but it would be worse to typecast it in my tasks implementations."

https://github.com/paulodamaso/donkey-tasks/blob/9987d09c4a333727d029f64148ca38a2bebeae68/src/java/main/Task.java#L11-L12

The puzzle was created by Paulo Lobo on 15-Dec-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
The puzzle `2-4e977bdc` has disappeared from the source code, that's why I closed this issue.

**Comment by paulodamaso** [comment]
Removing printable from task.
