### ISSUE TITLE
ConsoleTaskList.java:10: <body>still smelly, it's a...

### ISSUE THREAD

**Issue by 0pdd** [paulodamaso/donkey-tasks#8]
The puzzle `6-a91f86e8` (from #6) in [`src/java/main/ConsoleTaskList.java`](https://github.com/paulodamaso/donkey-tasks/blob/945747994e39a21d7e8a03b9bc26d1b22dfa6bfb/src/java/main/ConsoleTaskList.java#L10-L10) has to be resolved: "still smelly, it's a bridge in disguise: ConsoleTasks only handle ConsoleTask"

https://github.com/paulodamaso/donkey-tasks/blob/945747994e39a21d7e8a03b9bc26d1b22dfa6bfb/src/java/main/ConsoleTaskList.java#L10-L10

The puzzle was created by Paulo Lobo on 15-Dec-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by paulodamaso** [comment]
That's the way it's supposed to work; no smell here.
