### ISSUE TITLE
PostItTasks.java:10: <body>still smelly, it's a bridge in...

### ISSUE THREAD

**Issue by 0pdd** [paulodamaso/donkey-tasks#9]
The puzzle `6-c9954166` (from #6) in [`src/java/main/PostItTasks.java`](https://github.com/paulodamaso/donkey-tasks/blob/945747994e39a21d7e8a03b9bc26d1b22dfa6bfb/src/java/main/PostItTasks.java#L10-L10) has to be resolved: "still smelly, it's a bridge in disguise: PostItTasks only handle PostItTask"

https://github.com/paulodamaso/donkey-tasks/blob/945747994e39a21d7e8a03b9bc26d1b22dfa6bfb/src/java/main/PostItTasks.java#L10-L10

The puzzle was created by Paulo Lobo on 15-Dec-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by paulodamaso** [comment]
Created PrintableTask in attempt to remove this smell.

**Comment by paulodamaso** [comment]
It works this way, there's no smell.
